# Site settings
# Any variables here can be accessed in HTML files via {{site.myVariable}}

title: BLOG.

description: >- # this means to ignore newlines until "baseurl:"
  Writings and such.

baseurl: "" # the subpath of your site, e.g. /blog

url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: aNewPseudonym
github_username: aNewPseudonym
email: frdicapio01@gmail.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  - diary_entries

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
